import "./globals.css";
import { Inter } from "next/font/google";
import { TwNav } from "@/components/twNav";
import { Footer } from "@/components/footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body class="min-h-screen flex flex-col justify-between" className={inter.className}>
        <>
          <TwNav />
          <main class="flex-grow">{children}</main>
          <Footer />
        </>
      </body>
    </html>
  );
}
